stages:

  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/pipeline/__init__.py
      - yamlfiles/config.yaml
    outs:
      - artifacts/data_ingestion/brain_tumor_dataset

  prepare_base_model:
    cmd: python src/components/prepare_basemodel.py
    deps:
      - src/pipeline/__init__.py
      - yamlfiles/param.yaml
    params:
      - yamlfiles/param.yaml: [IMAGE_SIZE, WEIGHTS, INCLUDETOP, CLASSICS, LEARNING_RATE]
    outs:
      - artifacts/prepare_base_model/vgg16.keras
      - artifacts/prepare_base_model/update_base_mode.keras

  prepare_callbacks:
    cmd: python src/components/callbacks.py
    deps:
      - src/pipeline/__init__.py
      - src/entity/config.py
      - yamlfiles/config.yaml
    outs:
      - artifacts/prepare_callbacks/tensorboard_log_dir
      - artifacts/prepare_callbacks/checkpoint_
    
  model_training:
    cmd: python src/components/model_training.py
    deps:
      - src/pipeline/__init__.py
      - src/components/callbacks.py
      - yamlfiles/config.yaml
      - artifacts/prepare_base_model/update_base_mode.keras
      - artifacts/data_ingestion/archive/brain_tumor_dataset
    params:
      - yamlfile/param.yaml: [LEARNING_RATE, BATCH_SIZE, EPOCHS, AUGMENTATION]
    outs:
      - artifacts/training/model.keras
 